Repository Sybit-Education/Diveni, pull requests merged in 2022-10, with the labels that each got.

#227 Replace maven wtih gradle
  .github/workflows/backend.yaml
  README.md
  backend/.gitignore
  backend/.mvn/wrapper/MavenWrapperDownloader.java
  backend/.mvn/wrapper/maven-wrapper.jar
  backend/.mvn/wrapper/maven-wrapper.properties
  backend/Dockerfile
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/mvnw
  backend/mvnw.cmd
  backend/pom.xml
  backend/settings.gradle
  docs/guide/contribution.md
  docs/guide/develop.md
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#237 fix: test workflow fails for pull-requests from forks
  .github/workflows/backend.yaml
Labels: bug, backend, hacktoberfest, HACKTOBERFEST-ACCEPTED

#235 Migrate from SpringFox to SpringDoc.
  backend/build.gradle
  backend/src/main/java/io/diveni/backend/config/SpringFoxConfig.java
  docs/guide/architecture.md
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#230 Add the link to the translation website in docs & aboutPage
  docs/guide/contribution.md
  frontend/src/components/navigation/LocaleDropdown.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/es.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/pl.json
  frontend/src/locales/pt.json
  frontend/src/locales/uk.json
  frontend/src/views/AboutPage.vue
Labels: hacktoberfest

#239 New Crowdin updates
  frontend/src/locales/de.json
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#242 improved landing page
  frontend/src/assets/img/diveni-background.png
  frontend/src/components/LandingPageCard.vue
  frontend/src/components/navigation/FooterBar.vue
  frontend/src/components/navigation/TopNavigationBar.vue
  frontend/src/views/LandingPage.vue
Labels: frontend, hacktoberfest, HACKTOBERFEST-ACCEPTED

#244 Issue229 show result on last vote
  backend/src/main/java/io/diveni/backend/controller/WebsocketController.java
  frontend/src/views/SessionPage.vue
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED
