Repository Sybit-Education/Diveni, pull requests merged in 2023-04, with the labels that each got.

#238 224: add filter to the Session Page and also some translations
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/magnifying glass.png
  frontend/src/components/ProjectSelectionComponent.vue
  frontend/src/components/UserStories.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/es.json
  frontend/src/locales/fr.json
  frontend/src/locales/it.json
  frontend/src/locales/pl.json
  frontend/src/locales/pt.json
  frontend/src/locales/uk.json
  frontend/src/views/SessionPage.vue
Labels: hacktoberfest

#281 #279 SSH: switch from password to key authentication
  .github/workflows/diveni-deploy.yml
Labels: deployment

#280 #278 Fix docker images are not built
  .github/workflows/diveni-deploy.yaml
  .github/workflows/diveni-deploy.yml
  .github/workflows/github-housekeeping.yaml
  .github/workflows/remove-artifacts.yaml
  .github/workflows/vuepress-deploy.yaml
Labels: bug, deployment
